receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/prom/push"
    tls:
      insecure: true
  otlp:
    endpoint: "http://tempo:4417"
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
  logging/metrics:
    verbosity: detailed
  logging/traces:
    verbosity: detailed
  logging/logs:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
#      exporters: [otlp,logging/traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
#      exporters: [prometheusremotewrite,logging/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
#      exporters: [loki,logging/logs]